/**
 * GENERATED by scripts/drink-metrics.mjs — do not edit by hand.
 *
 * Where the drink sits inside its artwork, as fractions of the canvas. The
 * files share a 1080×720 canvas and draw their glasses at true relative scale
 * on one baseline, so the canvas is the right unit for SIZE; these bounds are
 * what the halo, the reflection and the contact shading need instead, because
 * a glass fills anywhere from 11% to 57% of the frame it is drawn on.
 */
export interface DrinkBounds {
  /** Left edge of the drawn glass, 0-1 across the canvas width. */
  left: number;
  /** Right edge, 0-1. */
  right: number;
  /** Top edge, 0-1 down the canvas height. */
  top: number;
  /** The base the glass stands on, 0-1 down the canvas height. */
  bottom: number;
}

export const DRINK_BOUNDS: Record<string, DrinkBounds> = {
  "americano": { left: 0.3056, right: 0.7731, top: 0.2375, bottom: 0.9861 },
  "americano_extra_shot2": { left: 0.3056, right: 0.8556, top: 0.1125, bottom: 0.9861 },
  "black_eye": { left: 0.3065, right: 0.8556, top: 0.1125, bottom: 0.9875 },
  "cafe_au_lait": { left: 0.1769, right: 0.8213, top: 0.2056, bottom: 0.9917 },
  "cafe_creme": { left: 0.3065, right: 0.7731, top: 0.2375, bottom: 0.9861 },
  "cafe_creme_doppio": { left: 0.2991, right: 0.7741, top: 0.2375, bottom: 0.9861 },
  "caffe_latte": { left: 0.3065, right: 0.7731, top: 0.0944, bottom: 0.9861 },
  "cappuccino": { left: 0.2444, right: 0.8426, top: 0.3569, bottom: 0.9958 },
  "dead_eye": { left: 0.3056, right: 0.8556, top: 0.1125, bottom: 0.9861 },
  "espresso": { left: 0.3676, right: 0.6204, top: 0.55, bottom: 0.9847 },
  "espresso_doppio": { left: 0.3463, right: 0.6398, top: 0.5472, bottom: 0.9875 },
  "espresso_macchiato": { left: 0.3676, right: 0.6204, top: 0.55, bottom: 0.9847 },
  "flat_white": { left: 0.2444, right: 0.8426, top: 0.5, bottom: 0.9958 },
  "freestyle_placeholder": { left: 0.2602, right: 0.7389, top: 0.2097, bottom: 0.9861 },
  "latte_macchiato": { left: 0.2991, right: 0.7009, top: 0.0042, bottom: 0.9986 },
  "latte_macchiato_extra_shot2": { left: 0.2991, right: 0.8407, top: 0.0042, bottom: 0.9986 },
  "latte_macchiato_triple_shot2": { left: 0.2991, right: 0.8407, top: 0.0042, bottom: 0.9986 },
  "long_black": { left: 0.3056, right: 0.7731, top: 0.2153, bottom: 0.9861 },
  "lungo": { left: 0.3676, right: 0.6204, top: 0.55, bottom: 0.9847 },
  "milk": { left: 0.2991, right: 0.6889, top: 0.1236, bottom: 1 },
  "milk_froth": { left: 0.2991, right: 0.6889, top: 0.1236, bottom: 1 },
  "red_eye": { left: 0.3056, right: 0.8556, top: 0.1125, bottom: 0.9861 },
  "ristretto": { left: 0.3676, right: 0.6204, top: 0.55, bottom: 0.9847 },
  "ristretto_doppio": { left: 0.3463, right: 0.6398, top: 0.5472, bottom: 0.9875 },
  "water": { left: 0.2981, right: 0.9463, top: 0.1236, bottom: 1 },
};

/** The whole canvas — what an unmeasured drawing (a served IconSpec) fills. */
export const FULL_BOUNDS: DrinkBounds = { left: 0, right: 1, top: 0, bottom: 1 };
