/**
 * Measure where the drink actually sits inside each artwork file.
 *
 * Every recipe PNG is the same 1080×720 canvas and the drinks are drawn on it
 * at TRUE relative scale with a shared baseline — an espresso really is 0.44×
 * a latte macchiato, which is what makes rendering every file at one width
 * correct. But the glass occupies anywhere from 11% to 57% of that canvas, so
 * anything that has to hug the glass — the halo, the mirrored reflection, the
 * contact shading — cannot use the canvas as its measure.
 *
 * This writes those bounds, as fractions of the canvas, into a generated
 * module. Run it when the artwork changes:
 *
 *   node scripts/drink-metrics.mjs
 */
import { readdir, readFile, writeFile } from "node:fs/promises";
import { PNG } from "pngjs";
import { basename, join } from "node:path";

const DIR = "src/assets/recipes";
const OUT = "src/lib/drink-metrics.ts";
const ALPHA_FLOOR = 8;

const files = (await readdir(DIR)).filter((f) => f.endsWith(".png")).sort();
const rows = [];

for (const file of files) {
  const png = PNG.sync.read(await readFile(join(DIR, file)));
  const { width, height, data } = png;
  let left = width, right = -1, top = height, bottom = -1;
  for (let y = 0; y < height; y += 1) {
    for (let x = 0; x < width; x += 1) {
      if (data[(y * width + x) * 4 + 3] <= ALPHA_FLOOR) continue;
      if (x < left) left = x;
      if (x > right) right = x;
      if (y < top) top = y;
      if (y > bottom) bottom = y;
    }
  }
  if (right < 0) continue;
  const f = (n) => Number(n.toFixed(4));
  rows.push({
    key: basename(file, ".png"),
    left: f(left / width),
    right: f((right + 1) / width),
    top: f(top / height),
    bottom: f((bottom + 1) / height),
  });
}

const body = rows
  .map((r) => `  ${JSON.stringify(r.key)}: { left: ${r.left}, right: ${r.right}, top: ${r.top}, bottom: ${r.bottom} },`)
  .join("\n");

await writeFile(
  OUT,
  `/**
 * GENERATED by scripts/drink-metrics.mjs — do not edit by hand.
 *
 * Where the drink sits inside its artwork, as fractions of the canvas. The
 * files share a 1080×720 canvas and draw their glasses at true relative scale
 * on one baseline, so the canvas is the right unit for SIZE; these bounds are
 * what the halo, the reflection and the contact shading need instead, because
 * a glass fills anywhere from 11% to 57% of the frame it is drawn on.
 */
export interface DrinkBounds {
  /** Left edge of the drawn glass, 0-1 across the canvas width. */
  left: number;
  /** Right edge, 0-1. */
  right: number;
  /** Top edge, 0-1 down the canvas height. */
  top: number;
  /** The base the glass stands on, 0-1 down the canvas height. */
  bottom: number;
}

export const DRINK_BOUNDS: Record<string, DrinkBounds> = {
${body}
};

/** The whole canvas — what an unmeasured drawing (a served IconSpec) fills. */
export const FULL_BOUNDS: DrinkBounds = { left: 0, right: 1, top: 0, bottom: 1 };
`,
);

console.log(`wrote ${OUT} for ${rows.length} drinks`);
